### ISSUE TITLE
GeoNames Group - problem with creating/removing/editing/adding group again

### ISSUE THREAD

**Issue by LauraBeazley** [GatewayGeo/gCat#13]
Group was Deleted - but GN thinks it still exists when I try to add the group again. Error message: as per screengrab
<img width="929" alt="GeoNamesProgram Group was deleted but gCAt thinks it still exists" src="https://github.com/GatewayGeo/gCat/assets/163455748/57513fe8-b07a-40ca-ad10-83f2814ba0c3">

**Comment by jmckenna** [comment]
@LauraBeazley is this different than the issue I had already filed at #5 about the group problem?  (we need to make sure that we don't have duplicate issues - best to always perform a search of issues before opening new issues)

**Comment by LauraBeazley** [comment]
AH right - yes I believe it is definitely part of that package of issues. I was trying to create a new group with the name GeoNames Program- and it wouldn't let me because the GeoNamesProgram still exists in Geonetwork's "memory", but the group that does exist actually was changed to GeoNames_Program. So it thinks the deleted group from last week was changed. Now I can't remove this group because there is metadata attached to this group and I need to create a new group to transfer the metadata to! oh my! Next time I will review the issues as you suggest.
