### ISSUE TITLE
Map View - initial view is bare. Set to Nova Scotia extent?

### ISSUE THREAD

**Issue by LauraBeazley** [GatewayGeo/gCat#15]
When I first clicked on teh map view today - there was nothing loaded - a bare screen/no map.
<img width="937" alt="Default Initial Map View is Bare" src="https://github.com/GatewayGeo/gCat/assets/163455748/73edc831-0479-44e7-b6da-198c7f1e5ade">
Perhaps we could set the initial view to be Nova Scotia extent?
![Uploading Make default initial map view show Nova Scotia.PNG…]()

**Comment by jmckenna** [comment]
This was fixed earlier (initial map view extents were changed to NS).
