### ISSUE TITLE
gCat cannot access Elastic search service

### ISSUE THREAD

**Issue by LauraBeazley** [GatewayGeo/gCat#20]
Tried logging in yesterday - thought you might be doing something in there, but now today is the same - can't access gCat

<img width="929" alt="gCat is down-can't access" src="https://github.com/GatewayGeo/gCat/assets/163455748/ed07f03b-2b3b-43c5-9e64-1216f7a64acf">

**Comment by LauraBeazley** [comment]
i cleared cache and also screen refresh and still no access - will try another browser...

**Comment by LauraBeazley** [comment]
wow - fast and furious addressing of the issue or ? it works in firefox - and then i went bacl to Edge - and it all works now thanks! not sure what happened...

**Comment by jmckenna** [comment]
Yes sorry I fixed that earlier this morning.   We do have an issue where the index is not found, seems to happen once per week.  I'm going to leave this issue/ticket open, as I track down this tricky fix.

**Comment by jmckenna** [comment]
No longer an issue, closing.
