### ISSUE TITLE
Home Page - Dataset and Service Blue boxes disappeared - just text now

### ISSUE THREAD

**Issue by LauraBeazley** [GatewayGeo/gCat#21]
![Screenshot 2024-03-21 at 09-18-21 gCAT](https://github.com/GatewayGeo/gCat/assets/163455748/c23c7aac-db25-4e3d-ba57-6edddfcef886)
The blue boxes for Dataset and Service are now left justified text in Firefox, and looks the same in Edge as well - perhaps this is being worked on at the moment?

**Comment by jmckenna** [comment]
Yes, it's in the middle of development, apologies for the inconvenience, related to experimenting with static filters, related to issue #2

**Comment by jmckenna** [comment]
This issue was fixed earlier.
