### ISSUE TITLE
Error message while trying to publish a forestry record

### ISSUE THREAD

**Issue by LauraBeazley** [GatewayGeo/gCat#27]
<img width="768" alt="error message during publish forestry record" src="https://github.com/GatewayGeo/gCat/assets/163455748/53116efe-6226-4f87-a5ae-dd74f35308e6">
not sure if it actually published or not - will check

**Comment by LauraBeazley** [comment]
it did not publish

**Comment by jmckenna** [comment]
I battled this same error earlier today (it was related to the thumbnail images on the search results page not showing), I believe I "fixed it", but please re-open this issue if it comes back.
