### ISSUE TITLE
Error message during attempted indexing (manage record)

### ISSUE THREAD

**Issue by LauraBeazley** [GatewayGeo/gCat#28]
<img width="898" alt="error message during indexing forestry record" src="https://github.com/GatewayGeo/gCat/assets/163455748/da81ffff-55b5-4f2e-a91d-66165aa0043a">

**Comment by jmckenna** [comment]
I believe this was due to me tackling issue https://github.com/GatewayGeo/gCat/issues/27 and the server was busy at that moment, causing this. Closing this ticket now, but please re-open if that same error message comes back.
