### ISSUE TITLE
Error message during geonames record publish attempt

### ISSUE THREAD

**Issue by LauraBeazley** [GatewayGeo/gCat#29]
<img width="849" alt="error message during publish geonames record" src="https://github.com/GatewayGeo/gCat/assets/163455748/59ac68da-abec-4574-9799-c0af83bb3c2b">

The record did not publish, i tried as geonames editor and also as administrator
Seems like I cant publish anything - maybe something else changed in backend?

**Comment by jmckenna** [comment]
I believe this was due to me tackling issue #27 and the server was busy at that moment, causing this.  Closing this ticket now, but please re-open if that same error message comes back.
