### ISSUE TITLE
Enable "add to selection" (and "basket") functionality

### ISSUE THREAD

**Issue by jmckenna** [GatewayGeo/gCat#31]
This issue will track enabling the "add to selection" (and "basket") functionality in the "search" tab of gCat.

**Comment by jmckenna** [comment]
- I have enabled the "add to selection " functionality.  Now if you go to the "Search" page, you can click the box in the top-left, select multiple records, and then in the "selected" dropdown near the top, you can perform tasks on multiple records at once, such as "Publish" or "Delete" etc.

  ![select-gcat](https://github.com/GatewayGeo/gCat/assets/1611709/08e95a70-05bc-45e4-abd1-70f6525c52b4)

- This also enabled the little icon tools at the bottom of the search thumbnails, that allows you to add that record to map (the little globe icon), add to preferred list (basket in top left), etc.   

  ![thumbnail-icons-gcat](https://github.com/GatewayGeo/gCat/assets/1611709/f61fcd2f-fb10-493b-89ce-b44ce0cadee3)

- I also moved the "basket" to the top of the left panel (it was way at the very bottom of the left panel, by default, making it hard to notice)

  ![basket-gcat](https://github.com/GatewayGeo/gCat/assets/1611709/8bc025e5-4385-44d2-a902-4c887b5af6b1)

Give it a try @LauraBeazley !

**Comment by LauraBeazley** [comment]
Thanks for enabling all those bits.
More functionality to work with!
Ill give all a test drive/look.
LB
________________________________

**Comment by jmckenna** [comment]
Works well, closing.
