### ISSUE TITLE
Various front page teaser line changes

### ISSUE THREAD

**Issue by LauraBeazley** [GatewayGeo/gCat#41]
Changes: 
1)  Change gCAT to gCat
2)  Remove the gold texted word GeoNOVA
3)  Centre justify the text to align with the search bar
4)  Adjust the word Geographic Catalog (gCat) to be a bit larger than what it is now (make more prominent) and 
5)  Change the color of that text to be a dark blue instead of the current grey - again to make those words slightly more distinctive than what they are now.
(see attached pic)
Geographic Catalog (gCat)
The official source for Nova Scotia Government geographic information products
<img width="554" alt="teaser text mods" src="https://github.com/GatewayGeo/gCat/assets/163455748/e9f728b8-6bbb-4f28-a9b5-3bf20687a38e">

**Comment by LauraBeazley** [comment]
@jmckenna  maybe you could tackle this one - so that everyone has the same branding message at the June 27 meeting?

**Comment by jmckenna** [comment]
@LauraBeazley Fixed, as below, let me know what you think.

![home-new](https://github.com/GatewayGeo/gCat/assets/1611709/28f80c83-7076-41b2-a13f-355a787ca46c)

**Comment by jmckenna** [comment]
Minor tweaks, looks cleaner now...

![home-new2](https://github.com/GatewayGeo/gCat/assets/1611709/c9531551-3fe8-44e8-bbc3-82e4ca805bb6)

**Comment by LauraBeazley** [comment]
Looks great @jmckenna - thinking maybe the black number needs to be the same color as the text?

**Comment by jmckenna** [comment]
Updated.

![home-new3](https://github.com/GatewayGeo/gCat/assets/1611709/c1246f74-9305-4f19-91f8-91f91eabb619)
