### ISSUE TITLE
Add Provincial Logo to gCat front page and search page - before June 27 if possible

### ISSUE THREAD

**Issue by LauraBeazley** [GatewayGeo/gCat#44]
I just realized we don't have the provincial logo in gCat! it shoudl be on the front page as well as the search page.
A must have.  Thinking it could go in the lower right hand corner next to the Government of Nova Scotia words?
Here's an example of where the Provincial logo and the GeoNova logo's are in other apps:
https://nsgi.novascotia.ca/nscrs-viewer

If this can be done for the meeting on the 27 that would be fabulous!
Attached is a provincial logo sample from Communications Nova Scotia.

![nsvip-en](https://github.com/GatewayGeo/gCat/assets/163455748/08bac7bf-2672-4542-9a7d-d9e2c9706eb9)

**Comment by jmckenna** [comment]
- added to the bottom-right footer

Clear your cache, reload the page, & see!
