### ISSUE TITLE
Can't Delete Spatial Filter Draw Boxes on map preview 

### ISSUE THREAD

**Issue by LauraBeazley** [GatewayGeo/gCat#46]
I have tried to perform a search for records by drawing a spatial filter in the map preview, but I'm not sure how to do it. I can draw a box, and nothing happens, so then I draw another and another and many boxes keep piling up. I try to delete any of them with the eraser but ,cant seem to delete them. They stay in memory somehow because I'll leave gCat clear the cache and reload the screen and the boxes are still there. It is not intuitive how to delete these. I cant tell if its a user knowledge thing or the gCat is not performing correctly.

I would expect a spatial filter to find all the products that are within or intersect with the draw box - I'm assuming its the "geographic coordinates" spatial extent metadata field that would need to be populated for this search to work?

<img width="671" alt="cant delete spatial filter draw boxes in map preview" src="https://github.com/GatewayGeo/gCat/assets/163455748/f0154d36-36ea-4ddb-a7b0-39552ca982f5">

**Comment by jmckenna** [comment]
Closing, as we have figured out how to use the 'minimap'.
