### ISSUE TITLE
Make  words - Geographic Catalog (gCat) - same as front page and centre it

### ISSUE THREAD

**Issue by LauraBeazley** [GatewayGeo/gCat#49]
@jmckenna For consistency - please make the text below the search bar on the second search page the same as the front page.

<img width="681" alt="Change to blue text and make like front page" src="https://github.com/GatewayGeo/gCat/assets/163455748/3fd9715e-3e57-4d01-baeb-1d04c6bd08d3">
move gCat to other side, make it all blue

so it jsut says Geographic Catalog (gCat) like the front page maybe centre it too please :)

**Comment by jmckenna** [comment]
- fixed.  It should now appear similar to the home page (as below).

![search-new](https://github.com/GatewayGeo/gCat/assets/1611709/d76640be-5379-4f82-b366-5493997f8453)

**Comment by LauraBeazley** [comment]
Jeff - thanks so much for all of your help - above and beyond is what I see and that's super!

Stellar work on this initiative - THANK YOU so much for everything.

The chatter - and the amount of people who showed up was crazy awesome! I am getting great feedback about the demo.
And the stats! 39 ?? wow

We done good!

I'll be in touch soon.

Laura
________________________________
