### ISSUE TITLE
Adjust GeoNOVA logo to be in line with header text - also try transparent background logo OR a higher res logo

### ISSUE THREAD

**Issue by LauraBeazley** [GatewayGeo/gCat#50]
@jmckenna Could we try to use a transparent  GeoNOVA logo? The one there is low res pixely when I look at it on my larger screen.
Also could it be placed on the same line as the header text similar to how the provincial logo is in line with the footer text?
I have attached a couple logo version plus a higher resolution one - in case the transparent ones don't work.

Screengrab from gcat:
<img width="876" alt="Try a transparent logo on the same line as the rest of the header tabs" src="https://github.com/GatewayGeo/gCat/assets/163455748/b7199131-7010-45e0-8e87-d5cabac9349f">

Transparent logo #1 
![GeoNOVA_logo_fromJPGtoPNG-no background](https://github.com/GatewayGeo/gCat/assets/163455748/447faa37-bdda-4425-8bdf-e23cd6591e19)

A JPG - with white background:
![GeoNOVA_logo_JPG](https://github.com/GatewayGeo/gCat/assets/163455748/6dfc6e45-3bb2-411c-b4f6-d092ff8ce3d0)

**Comment by jmckenna** [comment]
- adjusted to use a higher-res logo, and positioned within the header (as below)
- if you right-click that logo in your browser, you can see the full-res logo used: https://gcat.gatewaygeo.ca/geonetwork/images/logos/a3cf21b4-0a5d-47ed-82b6-67ce34986e8a.png
- 
![header-logo](https://github.com/GatewayGeo/gCat/assets/1611709/35d72de1-4e33-498d-b5f0-10d914136fb7)
